#+TITLE: 2022-02-16

* What did I do today
- Sent signup story for review
- Had a look at the nilenso website progress (to see if I can help)
- G&L with Shivam
* What will I do tomorrow
- Pick up login story
* Blockers
- The Heroku staging server seems to be broken because of some billing issue. This has blocked QA.
- I would prefer having my signup [[https://github.com/nilenso/bugle-forms/pull/8][PR]] reviewed before I start implementing the login story. It would be nice if this can be done before my pairing session with Srihari tomorrow.
* TIL (+ commentary)
** Installing Ruby on mac
Easily the worst installation experience I had in a long time. I wanted to see if I can help with the new website development (since I am blocked till review anyway). I needed ruby to build the website. Turns out the default ruby on mac is old and caused some file permission errors when trying to install bundle. Then I scoured the internet and got recommended =chruby= + =ruby-install= to install and manage rubies. Did that. Still broken. Why? Here's a story in commandline (abbreviated for flow):
#+begin_src
$ ruby-install
<downloads a bunch of stuff to show me stable ruby versions>
$ ruby-install 3.1.0   # latest stable

$ cd nilenso.com
$ make serve
bundle exec middleman
bundler: command not found: middleman
Install missing gem executables with `bundle install`
make: *** [serve] Error 127

$ bundle install  # just doing what the prompt told me
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Your Ruby version is 3.1.0, but your Gemfile specified 2.6.3

$ ruby-install 2.6.3  # let's try to match the ruby in the Gemfile
<long makefile compilation dump that ran for 5ish mins>
<COMPILE ERROR. wot.>

$ ruby-install 2.6.9  # let's try to use the nearest stable version with same minor version
<this one compiled successfully>

$ chruby ruby-2.6.9
$ bundle install
/Users/atharva/.rubies/ruby-2.6.9/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.1.4) required by your /Users/atharva/nilenso.com/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
	from /Users/atharva/.rubies/ruby-2.6.9/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	from /Users/atharva/.rubies/ruby-2.6.9/bin/bundle:23:in `<main>'

$ bundle update --bundler  # uhh, lemme try updating?
You must use Bundler 2 or greater with this lockfile.

$ gem install bundler:2.1.4  # okay, install it is then, as the prompt says
Fetching bundler-2.1.4.gem
Successfully installed bundler-2.1.4
Parsing documentation for bundler-2.1.4
Installing ri documentation for bundler-2.1.4
Done installing documentation for bundler after 1 seconds
1 gem installed

$ bundle install
Your Ruby version is 2.6.9, but your Gemfile specified 2.6.3

$ bundle update --bundler
Your Ruby version is 2.6.9, but your Gemfile specified 2.6.3

$ rm -rf --no-preserve-root /
#+end_src

UPDATE: wow ok, so I shouldn't have tried all this from the master branch, which is the legacy website. I switched over to =v2= and it's fine ...because it does not need ruby.
